server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

wechat:
  app-id: ${WECHAT_APPID}
  app-secret: ${WECHAT_APPSECRET}

# 文件上传配置
file:
  upload:
    dir: uploads
    avatar:
      path: avatar
  access:
    base-url: ${FILE_ACCESS_BASE_URL:}